url: https://y7kim.github.io
baseurl: /fellowship/

# Site settings
title: The METRO Fellowship
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00ffbf
  secondary: ff00ff 
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/mnylc
  - title: facebook
    url:
  - title: github
    url: https://github.com/mnylc

# Postal address (add as many lines as necessary)
address:
  - line: 57 East 11th Street 
  - line: New York, NY 10003

# Build settings
markdown: kramdown
permalink: pretty